export default [
  {
    position: "Software Engineer",
    company: "Playtech",
    logo: 'https://github.com/SVladikO/v-market/blob/master/src/image/company-logo/playtech.png?raw=true',
    fromDate: "Aug 2019",
    toDate: "Apr 2021",
    duration: "1 yr 9 mos",
    city: "Kiev Region",
    country: "Ukraine",
    responsibility: "I've worked on client side (configuration, branding, support, upgrade, bugfix).",
    skills: "JS, React, Node.js, HTML, CSS",
  },
  {
    position: "Front End Developer",
    company: "Astound Commerce",
    logo: 'https://github.com/SVladikO/v-market/blob/master/src/image/company-logo/astound.png?raw=true',
    fromDate: "Sep 2018",
    toDate: "Jun 2019",
    duration: "10 mos",
    city: "Kiev Region",
    country: "Ukraine",
    responsibility: "I’ve taken a part in develop two e-commerce projects(bugfix, brought new functionality).",
    skills: "JS, GitLab, Node.js, NPM, Jira",
  },
  {
    position: "Full Stack Developer",
    company: "Itera",
    logo: 'https://github.com/SVladikO/v-market/blob/master/src/image/company-logo/itera.png?raw=true',
    fromDate: "Sep 2017",
    toDate: "Jun 2018",
    duration: "10 mos",
    city: "Kiev Region",
    country: "Ukraine",
    responsibility: "I’ve taken a part in developing server & client side for Íslandsbanki (bugfix, tests, brought new functionality).",
    skills: "JS, Java 8, Angular.js, Node.js, Spring, Camel, REST, JSON, SoapUI, JUnit, HTML, CSS, bakckbase, BackbaseAndroid Studio, IntelliJ IDEA"
  },
  {
    position: "Full Stack Developer",
    company: "Kyiv Smart City",
    logo: 'https://github.com/SVladikO/v-market/blob/master/src/image/company-logo/kyiv-smart-city.png?raw=true',
    fromDate: "Jun 2016",
    toDate: "Jyl 2017",
    duration: "1 yr 1 mos",
    city: "Kiev Region",
    country: "Ukraine",
    responsibility: "I've taken a part in develop iGov and pdf editor online (bugfix, brought new functionality).",
    skills: "JS, Java, Node.js, Angular JS 1.5, Git, Jira, React, Redux, JQuery, JSON, HTML, CSS, Bootstrap",
  },
  {
    position: "Java Developer",
    company: "Big Fish Game",
    logo: 'https://github.com/SVladikO/v-market/blob/master/src/image/company-logo/big-fish-game.png?raw=true',
    fromDate: "May 2015",
    toDate: "Jun 2016",
    duration: "1 yr 2 mos",
    city: "Kiev Region",
    country: "Ukraine",
    responsibility: "I've taken a part in develop product that worked with Facebook API (bugfix, tests, brought new functionality)",
    skills: "Java, Spring MVC, MySql, PostgreSQL, Mongo, ActiveJdbc, Hibernate 4, REST, Jersey",
  }
];